### ISSUE TITLE
Error after generation

### ISSUE THREAD

**Issue by mflux** [Filarius/video2video#8]
Most recent version of A1111 with this extension. Used a 12s video. Once all the images are generated, I get this:

 Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 271, in _read_frame_data
        assert len(arr) == framesize
    AssertionError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\A1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\A1111\stable-diffusion-webui\modules\img2img.py", line 236, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "C:\A1111\stable-diffusion-webui\modules\scripts.py", line 700, in run
        processed = script.run(p, *script_args)
      File "C:\A1111\stable-diffusion-webui\extensions\video2video\scripts\vid2vid.py", line 241, in run
        raw_image = next(frame_generator,[])
      File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 297, in nextFrame
        yield self._readFrame()
      File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 281, in _readFrame
        s = self._read_frame_data()
      File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 275, in _read_frame_data
        raise RuntimeError("%s" % (err1,))
    RuntimeError

**Comment by Ribbles33** [comment]
I get exactly the same error, down to the line numbers, and the video file it created is invalid. I guess it's back to mov2mov for me.
